---
- name: Set up Nginx
  hosts: all

  tasks:
  - name: Install Nginx
    apt: name=nginx state=present

  - name: Configure Nginx
    template: src=homesite.conf.j2 dest=/etc/nginx/sites-enabled/test.conf
    with_items:
      port: 8001
      root: /home/vagrant
    notify:
      - restart nginx

  - name: Start Nginx
    service: name=nginx state=started

  handlers:
    - name: restart nginx
      service: name=httpd state=restarted
